### ISSUE TITLE
npm install fails on Node 0.12.x

### ISSUE THREAD

**Issue by louh** [h5bp/html5please#369]
The problem seems to be in execSync module which fails to compile with this message:

```
[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!
```

Here's an issue about it, and discussion: https://github.com/mgutz/execSync/issues/27

I solved the problem by using [n](https://github.com/tj/n) to switch to Node 0.10.x but it would be better if we didn't need to guess the solution. What's the recommended way of dealing with this? (a) upgrade / switch modules that are also compatible with 0.12.x (b) define the engine in package.json? does this actually do anything? (c) document this?

**Comment by arthurvr** [comment]
Yep. I needed a hacky solution due to a bug in the gulp compass plugin. I'll fix this up.

**Comment by luiscox** [comment]
I am also unable to run the npm run render and other commands, I get the following error:

```sh
module.js:338
    throw err;
          ^
Error: Cannot find module './build/Release/shell'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mateusortiz/Projects/OpenSource/html5please/node_modules/execSync/index.js:30:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

cc @arthurvr
